---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bookworm
  amd64: ghcr.io/home-assistant/amd64-base-debian:bookworm
  armv7: ghcr.io/home-assistant/armv7-base-debian:bookworm
  i386: ghcr.io/home-assistant/i386-base-debian:bookworm
  armhf: ghcr.io/home-assistant/armhf-base-raspbian:bookworm
codenotary:
  signer: mirakuru@webtoucher.ru
  base_image: notary@home-assistant.io
args:
  PLAYWRIGHT_VERSION: 1.26.1
