---
name: "Playwright"
description: "Playwright server for remote scripts execution"
version: "0.2.1"
slug: "playwright"
init: false
arch:
  - aarch64
  - amd64
  - armv7
  - i386
  - armhf
url: https://github.com/webtoucher/hassio-addons/tree/master/playwright
startup: services
ports:
  8585/tcp: 8585
